name         'gini-tayu'
version      '0.1.1'
author       'Jochen Schalanda'
license      'Apache 2.0'
project_page 'https://github.com/gini/puppet-tayu'
source       'https://github.com/gini/puppet-tayu'
summary      'Puppet module for managing tayu'
description  'This module installs and manages tayu, a webservice for integrating PuppetDB with Rundeck. Check README.md for details.'
