name         'smarchive-tayu'
version      '0.1.0'
author       'Jochen Schalanda'
license      'Apache 2.0'
project_page 'https://github.com/smarchive/puppet-tayu'
source       'https://github.com/smarchive/puppet-tayu'
summary      'Puppet module for managing tayu'
description  'This module installs and manages tayu, a webservice for integrating PuppetDB with Rundeck. Check README.md for details.'
dependency   'puppetlabs/stdlib', '>= 2.0.0'
